allowBuilds:
  cn-font-split: true
  esbuild: true
  koffi: true
  protobufjs: true
  sharp: true
  workerd: true

ignoredBuiltDependencies:
  - koffi
  - protobufjs

onlyBuiltDependencies:
  - cn-font-split
  - esbuild
  - sharp
  - workerd
