allowBuilds:
  esbuild: true
  koffi: true
  lightningcss: true
  protobufjs: true
  sharp: true
  workerd: true

ignoredBuiltDependencies:
  - koffi
  - protobufjs

onlyBuiltDependencies:
  - esbuild
  - lightningcss
  - sharp
  - workerd
